### ISSUE TITLE
[BUG] 默认标题

### ISSUE THREAD

**Issue by chenanism** [SDchao/AutoVsCEnv_WPF#50]
## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

### debug.log
The remote name could not be resolved: 'sdchao.lanzous.com'
   at System.Net.HttpWebRequest.GetResponse()
   at AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) in D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:line 134
   at AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) in D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:line 20
   at AutoVsCEnv_WPF.Operators.Installer.StartInstall() in D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:line 61
   at AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) in D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:line 47

### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by SDchao** [comment]
#36
